import emsg from './emsg';
import nump from './nump';
import frma from './frma';
import mvhd from './mvhd';
import pdin from './pdin';
import urn from './urn';
import styp from './styp';
import stco from './stco';
import iloc from './iloc';
import stts from './stts';
import trun from './trun';
import pitm from './pitm';
import irot from './irot';
import tmax from './tmax';
import sgpd from './sgpd';
import btrt from './btrt';
import dec3 from './dec3';
import subs from './subs';
import mfro from './mfro';
import dref from './dref';
import dfLa from './dfLa';
import pmax from './pmax';
import sbgp from './sbgp';
import TrakReference from './TrakReference';
import singleitemtypereferencelarge from './singleitemtypereferencelarge';
import stss from './stss';
import clap from './clap';
import hvcC from './hvcC';
import elst from './elst';
import trpy from './trpy';
import totl from './totl';
import dimm from './dimm';
import kind from './kind';
import ispe from './ispe';
import CoLL from './CoLL';
import stsd from './stsd';
import payl from './payl';
import mehd from './mehd';
import payt from './payt';
import sdtp from './sdtp';
import a1lx from './a1lx';
import trex from './trex';
import mdhd from './mdhd';
import saiz from './saiz';
import tfra from './tfra';
import hdlr from './hdlr';
import vpcC from './vpcC';
import ipma from './ipma';
import drep from './drep';
import clli from './clli';
import dac3 from './dac3';
import iinf from './iinf';
import tmin from './tmin';
import rtp from './rtp';
import iref from './iref';
import tenc from './tenc';
import dmax from './dmax';
import lsel from './lsel';
import pasp from './pasp';
import tkhd from './tkhd';
import cslg from './cslg';
import stsz from './stsz';
import sdp from './sdp';
import colr from './colr';
import ctts from './ctts';
import meta from './meta';
import sthd from './sthd';
import tpay from './tpay';
import npck from './npck';
import stsc from './stsc';
import mfhd from './mfhd';
import tref from './tref';
import stz2 from './stz2';
import fiel from './fiel';
import maxr from './maxr';
import stsg from './stsg';
import tfhd from './tfhd';
import imir from './imir';
import smhd from './smhd';
import dmed from './dmed';
import singleitemtypereference from './singleitemtypereference';
import schm from './schm';
import infe from './infe';
import sidx from './sidx';
import prft from './prft';
import co64 from './co64';
import tsel from './tsel';
import padb from './padb';
import stsh from './stsh';
import stvi from './stvi';
import saio from './saio';
import cprt from './cprt';
import vmhd from './vmhd';
import avcC from './avcC';
import auxC from './auxC';
import TrackGroup from './TrackGroup';
import ssix from './ssix';
import url from './url';
import stdp from './stdp';
import tfdt from './tfdt';
import a1op from './a1op';
import senc from './senc';
import vttC from './vttC';
import txtC from './txtC';
import av1C from './av1C';
import ftyp from './ftyp';
import SmDm from './SmDm';
import leva from './leva';
import stri from './stri';
import elng from './elng';
import mdcv from './mdcv';
import trep from './trep';
import pixi from './pixi';
import pssh from './pssh';
import esds from './esds';
import tpyl from './tpyl';
import msrc from './trackgroups/msrc';
import prol from './samplegroups/prol';
import tsas from './samplegroups/tsas';
import dtrt from './samplegroups/dtrt';
import tele from './samplegroups/tele';
import avll from './samplegroups/avll';
import sync from './samplegroups/sync';
import avss from './samplegroups/avss';
import stsa from './samplegroups/stsa';
import alst from './samplegroups/alst';
import rash from './samplegroups/rash';
import roll from './samplegroups/roll';
import rap from './samplegroups/rap';
import scif from './samplegroups/scif';
import seig from './samplegroups/seig';
import mvif from './samplegroups/mvif';
import scnm from './samplegroups/scnm';
import vipr from './samplegroups/vipr';
import tscl from './samplegroups/tscl';
import enof from './qt/enof';
import clef from './qt/clef';
import prof from './qt/prof';
import tapt from './qt/tapt';
import stxt from './sampleentries/stxt';
import wvtt from './sampleentries/wvtt';
import mett from './sampleentries/mett';
import sbtt from './sampleentries/sbtt';
import sampleentry from './sampleentries/sampleentry';
import metx from './sampleentries/metx';
import stpp from './sampleentries/stpp';
import tx3g from './sampleentries/tx3g';
import piffLsm from './uuid/piff/piffLsm';
import piffTfrf from './uuid/piff/piffTfrf';
import piffTfxd from './uuid/piff/piffTfxd';
import piffTenc from './uuid/piff/piffTenc';
import piffSenc from './uuid/piff/piffSenc';
import piffPssh from './uuid/piff/piffPssh';

export default (BoxParser: any) => {
  sampleentry(BoxParser);
  emsg(BoxParser);
  nump(BoxParser);
  frma(BoxParser);
  mvhd(BoxParser);
  pdin(BoxParser);
  urn(BoxParser);
  styp(BoxParser);
  stco(BoxParser);
  iloc(BoxParser);
  stts(BoxParser);
  trun(BoxParser);
  pitm(BoxParser);
  irot(BoxParser);
  tmax(BoxParser);
  sgpd(BoxParser);
  btrt(BoxParser);
  dec3(BoxParser);
  subs(BoxParser);
  mfro(BoxParser);
  dref(BoxParser);
  dfLa(BoxParser);
  pmax(BoxParser);
  sbgp(BoxParser);
  TrakReference(BoxParser);
  singleitemtypereferencelarge(BoxParser);
  stss(BoxParser);
  clap(BoxParser);
  hvcC(BoxParser);
  elst(BoxParser);
  trpy(BoxParser);
  totl(BoxParser);
  dimm(BoxParser);
  kind(BoxParser);
  ispe(BoxParser);
  CoLL(BoxParser);
  stsd(BoxParser);
  payl(BoxParser);
  mehd(BoxParser);
  payt(BoxParser);
  sdtp(BoxParser);
  a1lx(BoxParser);
  trex(BoxParser);
  mdhd(BoxParser);
  saiz(BoxParser);
  tfra(BoxParser);
  hdlr(BoxParser);
  vpcC(BoxParser);
  ipma(BoxParser);
  drep(BoxParser);
  clli(BoxParser);
  dac3(BoxParser);
  iinf(BoxParser);
  tmin(BoxParser);
  rtp(BoxParser);
  iref(BoxParser);
  tenc(BoxParser);
  dmax(BoxParser);
  lsel(BoxParser);
  pasp(BoxParser);
  tkhd(BoxParser);
  cslg(BoxParser);
  stsz(BoxParser);
  sdp(BoxParser);
  colr(BoxParser);
  ctts(BoxParser);
  meta(BoxParser);
  sthd(BoxParser);
  tpay(BoxParser);
  npck(BoxParser);
  stsc(BoxParser);
  mfhd(BoxParser);
  tref(BoxParser);
  stz2(BoxParser);
  fiel(BoxParser);
  maxr(BoxParser);
  stsg(BoxParser);
  tfhd(BoxParser);
  imir(BoxParser);
  smhd(BoxParser);
  dmed(BoxParser);
  singleitemtypereference(BoxParser);
  schm(BoxParser);
  infe(BoxParser);
  sidx(BoxParser);
  prft(BoxParser);
  co64(BoxParser);
  tsel(BoxParser);
  padb(BoxParser);
  stsh(BoxParser);
  stvi(BoxParser);
  saio(BoxParser);
  cprt(BoxParser);
  vmhd(BoxParser);
  avcC(BoxParser);
  auxC(BoxParser);
  TrackGroup(BoxParser);
  ssix(BoxParser);
  url(BoxParser);
  stdp(BoxParser);
  tfdt(BoxParser);
  a1op(BoxParser);
  senc(BoxParser);
  vttC(BoxParser);
  txtC(BoxParser);
  av1C(BoxParser);
  ftyp(BoxParser);
  SmDm(BoxParser);
  leva(BoxParser);
  stri(BoxParser);
  elng(BoxParser);
  mdcv(BoxParser);
  trep(BoxParser);
  pixi(BoxParser);
  pssh(BoxParser);
  esds(BoxParser);
  tpyl(BoxParser);
  msrc(BoxParser);
  prol(BoxParser);
  tsas(BoxParser);
  dtrt(BoxParser);
  tele(BoxParser);
  avll(BoxParser);
  sync(BoxParser);
  avss(BoxParser);
  stsa(BoxParser);
  alst(BoxParser);
  rash(BoxParser);
  roll(BoxParser);
  rap(BoxParser);
  scif(BoxParser);
  seig(BoxParser);
  mvif(BoxParser);
  scnm(BoxParser);
  vipr(BoxParser);
  tscl(BoxParser);
  enof(BoxParser);
  clef(BoxParser);
  prof(BoxParser);
  tapt(BoxParser);
  stxt(BoxParser);
  wvtt(BoxParser);
  mett(BoxParser);
  sbtt(BoxParser);
  metx(BoxParser);
  stpp(BoxParser);
  tx3g(BoxParser);
  piffLsm(BoxParser);
  piffTfrf(BoxParser);
  piffTfxd(BoxParser);
  piffTenc(BoxParser);
  piffSenc(BoxParser);
  piffPssh(BoxParser);
};
