import emsg from './emsg';
import mvhd from './mvhd';
import urn from './urn';
import stco from './stco';
import stts from './stts';
import trun from './trun';
import sgpd from './sgpd';
import dref from './dref';
import sbgp from './sbgp';
import stss from './stss';
import elst from './elst';
import kind from './kind';
import stsd from './stsd';
import mehd from './mehd';
import trex from './trex';
import mdhd from './mdhd';
import hdlr from './hdlr';
import sampleentry from './sampleentry';
import tkhd from './tkhd';
import cslg from './cslg';
import stsz from './stsz';
import ctts from './ctts';
import stsc from './stsc';
import mfhd from './mfhd';
import tfhd from './tfhd';
import sidx from './sidx';
import co64 from './co64';
import stsh from './stsh';
import vmhd from './vmhd';
import avcC from './avcC';
import url from './url';
import tfdt from './tfdt';
import ftyp from './ftyp';
import elng from './elng';

export default (BoxParser: any) => {
  emsg(BoxParser);
  mvhd(BoxParser);
  urn(BoxParser);
  stco(BoxParser);
  stts(BoxParser);
  trun(BoxParser);
  sgpd(BoxParser);
  dref(BoxParser);
  sbgp(BoxParser);
  stss(BoxParser);
  elst(BoxParser);
  kind(BoxParser);
  stsd(BoxParser);
  mehd(BoxParser);
  trex(BoxParser);
  mdhd(BoxParser);
  hdlr(BoxParser);
  sampleentry(BoxParser);
  tkhd(BoxParser);
  cslg(BoxParser);
  stsz(BoxParser);
  ctts(BoxParser);
  stsc(BoxParser);
  mfhd(BoxParser);
  tfhd(BoxParser);
  sidx(BoxParser);
  co64(BoxParser);
  stsh(BoxParser);
  vmhd(BoxParser);
  avcC(BoxParser);
  url(BoxParser);
  tfdt(BoxParser);
  ftyp(BoxParser);
  elng(BoxParser);
};
