declare class DataStream {
    static endianness: string;
    static LITTLE_ENDIAN: string;
    static BIG_ENDIAN: string;
    static defaultEndian: string;
    static arrayBufferToString(arrayBuffer: ArrayBuffer): string;
    static stringToArrayBuffer(string: string): ArrayBuffer;
    static arrayBufferToHex(arrayBuffer: ArrayBuffer): string;
    static hexToArrayBuffer(hex: string): ArrayBuffer;
    static arrayBufferToBase64(arrayBuffer: ArrayBuffer): string;
    static base64ToArrayBuffer(base64: string): ArrayBuffer;
    static arrayBufferToInt(arrayBuffer: ArrayBuffer): number;
    static intToArrayBuffer(int: number): ArrayBuffer;
    static arrayBufferToUint(arrayBuffer: ArrayBuffer): number;
    static uintToArrayBuffer(uint: number): ArrayBuffer;
    static arrayBufferToFloat(arrayBuffer: ArrayBuffer): number;
    static floatToArrayBuffer(float: number): ArrayBuffer;
    static arrayBufferToDouble(arrayBuffer: ArrayBuffer): number;
    static doubleToArrayBuffer(double: number): ArrayBuffer;
    static arrayBufferToLong(arrayBuffer: ArrayBuffer): number;
    static longToArrayBuffer(long: number): ArrayBuffer;
    static arrayBufferToULong(arrayBuffer: ArrayBuffer): number;
    static uLongToArrayBuffer(uLong: number): ArrayBuffer;
    static arrayBufferToStringArray(arrayBuffer: ArrayBuffer): string[];
    static stringArrayToArrayBuffer(stringArray: string[]): ArrayBuffer;
    static arrayBufferToIntArray(arrayBuffer: ArrayBuffer): number[];
    static intArrayToArrayBuffer(intArray: number[]): ArrayBuffer;
    static arrayBufferToUintArray(arrayBuffer: ArrayBuffer): number[];
    static uintArrayToArrayBuffer(uintArray: number[]): ArrayBuffer;
    static arrayBufferToFloatArray(arrayBuffer: ArrayBuffer): number[];
    static floatArrayToArrayBuffer(floatArray: number[]): ArrayBuffer;
    static arrayBufferToDoubleArray(arrayBuffer: ArrayBuffer): number[];
    static doubleArrayToArrayBuffer(doubleArray: number[]): ArrayBuffer;
    static arrayBufferToLongArray(arrayBuffer: ArrayBuffer): number[];
    static longArrayToArrayBuffer(longArray: number[]): ArrayBuffer;
    static arrayBufferToULongArray(arrayBuffer: ArrayBuffer): number[];
    static uLongArrayToArrayBuffer(uLongArray: number[]): ArrayBuffer;
    static arrayBufferToStringMap(arrayBuffer: ArrayBuffer): Map<string, string>;
    static stringMapToArrayBuffer(stringMap: Map<string, string>): ArrayBuffer;
    static arrayBufferToIntMap(arrayBuffer: ArrayBuffer): Map<string, number>;
    static intMapToArrayBuffer(intMap: Map<string, number>): ArrayBuffer;
    static arrayBufferToUintMap(arrayBuffer: ArrayBuffer): Map<string, number>;
    static uintMapToArrayBuffer(uintMap: Map<string, number>): ArrayBuffer;
    static arrayBufferToFloatMap(arrayBuffer: ArrayBuffer): Map<string, number>;
    static floatMapToArrayBuffer(floatMap: Map<string, number>): ArrayBuffer;
    static arrayBufferToDoubleMap(arrayBuffer: ArrayBuffer): Map<string, number>;
    static doubleMapToArrayBuffer(doubleMap: Map<string, number>): ArrayBuffer;
    static arrayBufferToLongMap(arrayBuffer: ArrayBuffer): Map<string, number>;
    static longMapToArrayBuffer(longMap: Map<string, number>): ArrayBuffer;
    static arrayBufferToULongMap(arrayBuffer: ArrayBuffer): Map<string, number>;
    static uLongMapToArrayBuffer(uLongMap: Map<string, number>): ArrayBuffer;
}
