name: Close Issues

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  actions: write
  issues: write

jobs:
  stale:
    if: github.repository == 'gpac/mp4box.js'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 83
          days-before-close: 7
          days-before-pr-stale: -1
          days-before-pr-close: -1
          exempt-issue-labels: "enhancement,question,box request,bug"
          stale-issue-label: "stale"

  action:
    if: github.repository == 'gpac/mp4box.js'
    needs: stale
    runs-on: ubuntu-latest
    steps:
      - name: Lock Inactive Issues
        uses: dessant/lock-threads@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-inactive-days: "180"
          issue-lock-reason: ""
          process-only: "issues"
