name: Publish

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/test.yml

  publish:
    if: github.repository == 'gpac/mp4box.js'
    name: release
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Pages
        uses: actions/configure-pages@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm

      - run: npm clean-install
      - run: npm install --global corepack@latest
      - run: corepack npm audit signatures
      - run: npm run build

      - name: Create publish directory
        run: |
          mkdir -p ${{ runner.temp }}/public
          mv ${{ github.workspace }}/dist ${{ runner.temp }}/public
          mv ${{ github.workspace }}/demo ${{ runner.temp }}/public/test

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: ${{ runner.temp }}/public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v5
