name: Release

on:
  push:
    branches:
      - main
      - next

env:
  PUBLISH_MODE: true

concurrency:
  group: "release"
  # Prevent semantic-release from being cancelled abruptly
  cancel-in-progress: false

jobs:
  release:
    if: github.repository == 'gpac/mp4box.js'
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    name: release
    runs-on: ubuntu-latest
    environment:
      name: npm
      url: https://www.npmjs.com/package/mp4box
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm

      - run: npm clean-install
      - run: npm install --global corepack@latest
      - run: corepack npm audit signatures
      - run: npm run build

      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          publish: npm run release
          commit: "ci: release"
          title: "[ci] release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
