name: Test

on:
  push:
    branches:
      - main
      - next
  pull_request:
    types:
      - opened
      - synchronize
  workflow_call:

permissions:
  contents: read

env:
  FORCE_COLOR: 1
  NPM_CONFIG_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: npm

      - run: npm clean-install
      - run: npm install --global corepack@latest
      - run: corepack npm audit signatures

      - name: Run Preliminary Checks
        run: npm run check

      - name: Run Tests
        run: npm test
