name: Test

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
  workflow_call:

permissions:
  contents: read

env:
  FORCE_COLOR: 1
  NPM_CONFIG_COLOR: always

jobs:
  # verify against ranges defined as supported in engines.node
  test_matrix:
    strategy:
      matrix:
        node-version:
          - 20.8.1
          - 20
          - 22.0.0

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: ${{ matrix.node-version }}

      - run: npm clean-install
      - run: npm install --global corepack@latest
      - run: corepack npm audit signatures

      - name: Run tests
        run: npm test
