name: Test

on:
  push:
    branches:
      - main
      - next
  pull_request:
    types:
      - opened
      - synchronize
  merge_group:
  workflow_call:

permissions:
  contents: read

env:
  FORCE_COLOR: 1
  NPM_CONFIG_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm

      - run: npm clean-install
      - run: npm install --global corepack@latest
      - run: corepack npm audit signatures
      - run: npm run format:check
      - run: npm run lint
      - run: npm run build
      - run: npm run circular
      - run: npm run test
